### ISSUE TITLE
Parsing unicode

### ISSUE THREAD

**Issue by dbrody2004** [BlakeStevenson/populartimes.js#19]
Not sure how widespread this is.  Code is trying to parse based on spaces.  Looks like one of those spaces was changed to unicode 0x202f (a short space) which breaks parsing in code.  Ended up replacing that unicode with a space.

<img width="385" alt="Screenshot 2023-02-09 at 7 22 19 PM" src="https://user-images.githubusercontent.com/4682241/217992756-f937412f-7558-49eb-b78b-13fde98fd096.png">

<img width="473" alt="Screenshot 2023-02-09 at 7 22 09 PM" src="https://user-images.githubusercontent.com/4682241/217992758-2c0ab406-014d-4d9d-9ced-994d7c38d136.png">

**Comment by BlakeStevenson** [comment]
Should be fixed in 28a7617. Thanks!
